services:
  mongo:
    image: mongo
    container_name: todo_uai_mongo
    restart: unless-stopped
    ports:
      - "${MONGO_PORT_EXT}:${MONGO_PORT_INT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_todo_uai_data:/data/db
    networks:
      - todo_uai_network

    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s 

  api:
    build: .
    container_name: todo_uai_api
    ports:
      - '${PORT}:${PORT}'
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - MONGODB_URI=${MONGODB_URI}
      - SESSION_SECRET=${SESSION_SECRET}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS}
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX}
      - LIMIT_BODY=${LIMIT_BODY}
      - LIMIT_URL=${LIMIT_URL}
      - BASE_URL=${BASE_URL}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - AUTH_SUCCESS_REDIRECT_URL=${AUTH_SUCCESS_REDIRECT_URL}
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - todo_uai_network
  
  # Just for development
  # mongo-express:
  #   image: mongo-express
  #   container_name: mongo-express-todo-uai
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  #     ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  #     ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  #     ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:${MONGO_PORT_INT}/
  #   depends_on:
  #     - mongo

networks:
  todo_uai_network:
    driver: bridge

volumes:
  mongo_todo_uai_data:  